Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, ax = plt.subplots(dpi=200,figsize=(5,5))

with gw.config.update(ref_res=100):
    with gw.open(l8_224078_20200518) as src:
        X, clf = fit(src, pl, labels, col="lc")
        y = predict(src, X, clf)
        y.plot(robust=True, ax=ax)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Input [0;32mIn [6][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      3[0m [38;5;28;01mwith[39;00m gw[38;5;241m.[39mconfig[38;5;241m.[39mupdate(ref_res[38;5;241m=[39m[38;5;241m100[39m):
[1;32m      4[0m     [38;5;28;01mwith[39;00m gw[38;5;241m.[39mopen(l8_224078_20200518) [38;5;28;01mas[39;00m src:
[0;32m----> 5[0m         X, clf [38;5;241m=[39m fit(src, pl, labels, col[38;5;241m=[39m[38;5;124m"[39m[38;5;124mlc[39m[38;5;124m"[39m)
[1;32m      6[0m         y [38;5;241m=[39m predict(src, X, clf)
[1;32m      7[0m         y[38;5;241m.[39mplot(robust[38;5;241m=[39m[38;5;28;01mTrue[39;00m, ax[38;5;241m=[39max)

[0;31mValueError[0m: too many values to unpack (expected 2)
ValueError: too many values to unpack (expected 2)

