Traceback (most recent call last):
  File "/home/mmann1123/anaconda3/envs/pygisbook_new/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/mmann1123/anaconda3/envs/pygisbook_new/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mmann1123/anaconda3/envs/pygisbook_new/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mmann1123/anaconda3/envs/pygisbook_new/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/mmann1123/anaconda3/envs/pygisbook_new/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/mmann1123/anaconda3/envs/pygisbook_new/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/mmann1123/anaconda3/envs/pygisbook_new/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/mmann1123/anaconda3/envs/pygisbook_new/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import geowombat as gw
from geowombat.data import l8_224078_20200518, l8_224078_20200518_polygons
from geowombat.ml import fit, predict, fit_predict
import geopandas as gpd
from sklearn_xarray.preprocessing import Featurizer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import PCA
from sklearn.naive_bayes import GaussianNB

le = LabelEncoder()

# The labels are string names, so here we convert them to integers
labels = gpd.read_file(l8_224078_20200518_polygons)
labels['lc'] = le.fit(labels.name).transform(labels.name)
print(labels)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn [1], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mgeowombat[39;00m [38;5;28;01mas[39;00m [38;5;21;01mgw[39;00m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mgeowombat[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdata[39;00m [38;5;28;01mimport[39;00m l8_224078_20200518, l8_224078_20200518_polygons
[0;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mgeowombat[39;00m[38;5;21;01m.[39;00m[38;5;21;01mml[39;00m [38;5;28;01mimport[39;00m fit, predict, fit_predict
[1;32m      4[0m [38;5;28;01mimport[39;00m [38;5;21;01mgeopandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mgpd[39;00m
[1;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn_xarray[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpreprocessing[39;00m [38;5;28;01mimport[39;00m Featurizer

File [0;32m~/anaconda3/envs/pygisbook_new/lib/python3.10/site-packages/geowombat/ml/__init__.py:1[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mclassifiers[39;00m [38;5;28;01mimport[39;00m Classifiers
[1;32m      3[0m fit [38;5;241m=[39m Classifiers()[38;5;241m.[39mfit
[1;32m      4[0m fit_predict [38;5;241m=[39m Classifiers()[38;5;241m.[39mfit_predict

File [0;32m~/anaconda3/envs/pygisbook_new/lib/python3.10/site-packages/geowombat/ml/classifiers.py:11[0m
[1;32m      9[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpipeline[39;00m [38;5;28;01mimport[39;00m Pipeline
[1;32m     10[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpreprocessing[39;00m [38;5;28;01mimport[39;00m LabelEncoder
[0;32m---> 11[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn_xarray[39;00m [38;5;28;01mimport[39;00m wrap, Target
[1;32m     14[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnp[39;00m
[1;32m     15[0m [38;5;28;01mfrom[39;00m [38;5;21;01mgeopandas[39;00m[38;5;21;01m.[39;00m[38;5;21;01mgeodataframe[39;00m [38;5;28;01mimport[39;00m GeoDataFrame

[0;31mModuleNotFoundError[0m: No module named 'sklearn_xarray'
ModuleNotFoundError: No module named 'sklearn_xarray'

